In [1]:
import pandas as pd
import numpy as np

In [2]:
b=pd.read_csv('C:\\Users\\santh\\Downloads\\Real estate.csv')

In [3]:
b=b.drop(['No','X1 transaction date'],axis=1)

In [4]:
b.head()

X2 house age  X3 distance to the nearest MRT station  \
0          32.0                                84.87882   
1          19.5                               306.59470   
2          13.3                               561.98450   
3          13.3                               561.98450   
4           5.0                               390.56840   

   X4 number of convenience stores  X5 latitude  X6 longitude  \
0                               10     24.98298     121.54024   
1                                9     24.98034     121.53951   
2                                5     24.98746     121.54391   
3                                5     24.98746     121.54391   
4                                5     24.97937     121.54245   

   Y house price of unit area  
0                        37.9  
1                        42.2  
2                        47.3  
3                        54.8  
4                        43.1

In [5]:
b.dtypes

X2 house age                              float64
X3 distance to the nearest MRT station    float64
X4 number of convenience stores             int64
X5 latitude                               float64
X6 longitude                              float64
Y house price of unit area                float64
dtype: object

In [6]:
for i in b:
    b[i].fillna(b[i].mean(),inplace=True)

In [7]:
b.isnull().sum().sort_values

<bound method Series.sort_values of X2 house age                              0
X3 distance to the nearest MRT station    0
X4 number of convenience stores           0
X5 latitude                               0
X6 longitude                              0
Y house price of unit area                0
dtype: int64>

In [8]:
b=b.astype(int)

In [9]:
b.dtypes

X2 house age                              int32
X3 distance to the nearest MRT station    int32
X4 number of convenience stores           int32
X5 latitude                               int32
X6 longitude                              int32
Y house price of unit area                int32
dtype: object

In [10]:
b

X2 house age  X3 distance to the nearest MRT station  \
0              32                                      84   
1              19                                     306   
2              13                                     561   
3              13                                     561   
4               5                                     390   
..            ...                                     ...   
409            13                                    4082   
410             5                                      90   
411            18                                     390   
412             8                                     104   
413             6                                      90   

     X4 number of convenience stores  X5 latitude  X6 longitude  \
0                                 10           24           121   
1                                  9           24           121   
2                                  5           24           121   
3                                  5           24           121   
4                                  5           24           121   
..                               ...          ...           ...   
409                                0           24           121   
410                                9           24           121   
411                                7           24           121   
412                                5           24           121   
413                                9           24           121   

     Y house price of unit area  
0                            37  
1                            42  
2                            47  
3                            54  
4                            43  
..                          ...  
409                          15  
410                          50  
411                          40  
412                          52  
413                          63  

[414 rows x 6 columns]

In [12]:
X=b.drop(['Y house price of unit area'],axis=1)

In [13]:
y=b['Y house price of unit area']

In [14]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.25,random_state=42)

In [15]:
from sklearn.linear_model import LinearRegression
lo=LinearRegression()

In [16]:
lo.fit(X_train,y_train)

LinearRegression()

In [17]:
y_pred=lo.predict(X_test)
y_pred

array([49.37677288, 43.45483261, 42.70663688, 40.37320092, 29.51264443,
       43.08025786, 44.12467892, 43.88080481, 28.88359265, 52.61602092,
       31.72614041, 33.63132275, 33.69370819, 28.80375854, 34.28839725,
       32.35420662, 43.13861286, 50.96068096, 31.10130417, 46.16949504,
        0.48009983, 32.53664607, 45.98747397, 45.73177662, 15.87519411,
       40.2762595 , 15.84497142, 42.70663688, 38.72352338, 35.85485667,
       11.11252037, 36.74048107, 40.6818907 , 31.81612576, 44.97734454,
       31.16114607, 52.85989503, 16.53097426, 46.10893414, 41.70083923,
       33.72222259, 39.95680756, 47.59993124, 37.61318334, 43.45483261,
       48.22579306, 46.58440373, 24.65257389, 51.63660957, 47.58282393,
       49.37677288, 46.51513925, 39.97475011, 43.18027893, 36.84217636,
       16.53097426, 37.69176232, 34.05052993, 29.51264443, 43.88080481,
       32.74003221, 30.00765528, 16.53097426, 11.26781679,  3.12583914,
       32.53664607, 33.09955375, 46.83090061, 33.14456604, 33.58

In [18]:
import numpy as np
print(np.unique(y))

[  7  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  67  69  70  71  73  78 117]


In [19]:
data=[[13,5082,0,24,121]]
data1=[[19,306,9,24,121]]
data2=[[34,504,22,24,132]]

In [20]:
lo.predict(data)

C:\Users\santh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([10.82853816])

In [21]:
lo.predict(data1)

C:\Users\santh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([48.2139313])

In [22]:
lo.predict(data2)

C:\Users\santh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([60.20223055])

In [23]:
import pickle

In [24]:
pickle_name='lr_model.pkl'
with open(pickle_name,"wb")as file:
    pickle.dump(lo,file)

In [25]:
with open("lr_model.pkl","rb") as f:
    model=pickle.load(f)

In [26]:
data=[[13,50,0,24,121]]
model.predict(data)

C:\Users\santh\anaconda3\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([39.52319658])